# Generated by Django 3.2.13 on 2022-04-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_number',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
