# Generated by Django 3.2.13 on 2022-04-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
