# Generated by Django 3.2.13 on 2022-04-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_employee_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_table', models.IntegerField()),
                ('no_of_chair', models.IntegerField()),
            ],
        ),
    ]
